# Generated by Django 2.1 on 2018-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beef',
            name='name',
            field=models.TextField(default='beef name'),
        ),
    ]
