# Generated by Django 2.1 on 2018-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beef', '0002_beef_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beef',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
