# Generated by Django 2.1 on 2018-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='name',
            field=models.CharField(default='Chickenstuff', max_length=255),
        ),
    ]
